### PR TITLE
Updated FSiAdminBundle to 1.1.*.

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by chives** [comment]
@szymach please remove php 5.3 and add php 5.6 to travis build matrix. You can also add hhvm with ``allowed_failures``

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Comment by JarekW** [comment]
:+1:

**Comment by szymach** [comment]
@fsi-open

**Comment by rn0** [comment]
:+1:

**Comment by szymach** [comment]
@fsi-open merge?

**Comment by chives** [comment]
:+1:

**Pull request merged**
